### ISSUE TITLE
FreeBSD 13-B4 vnet does not work

### ISSUE THREAD

**Issue by zenny** [genneko/freebsd-vimage-jails#2]
Hi,

I tried to deploy isolated VNET part (https://genneko.github.io/playing-with-bsd/system/learning-notes-on-jails/#vnet-jails) with no changes to your configs. However, I get this:

```
[root@freebsd13 ~]# vnet list -r
vi1
ifconfig: interface vi1_r1 does not exist
ifconfig: interface vi1_r1 does not exist
  freebsd13(HOST) vi1_r1
ifconfig: interface vi1_vpnr1 does not exist
ifconfig: interface vi1_vpnr1 does not exist
  freebsd13(HOST) vi1_vpnr1
vi2
ifconfig: interface vi2_r1 does not exist
ifconfig: interface vi2_r1 does not exist
  freebsd13(HOST) vi2_r1
ifconfig: interface vi2_vpnr2 does not exist
ifconfig: interface vi2_vpnr2 does not exist
  freebsd13(HOST) vi2_vpnr2
vri1
ifconfig: interface vri1_vpnh1 does not exist
ifconfig: interface vri1_vpnh1 does not exist
  freebsd13(HOST) vri1_vpnh1
ifconfig: interface vri1_vpnr1 does not exist
ifconfig: interface vri1_vpnr1 does not exist
  freebsd13(HOST) vri1_vpnr1
vri2
ifconfig: interface vri2_vpnh2 does not exist
ifconfig: interface vri2_vpnh2 does not exist
  freebsd13(HOST) vri2_vpnh2
ifconfig: interface vri2_vpnr2 does not exist
ifconfig: interface vri2_vpnr2 does not exist
  freebsd13(HOST) vri2_vpnr2
[root@freebsd13 ~]# vnet list
vi1
vi2
vri1
vri2
```

A look at dmesg shows:

```
...
WARNING: attempt to domain_add(netgraph) after domainfinalize()
ngeth0: Ethernet address: 58:9c:fc:10:ff:de
ngeth0: link state changed to UP
ngeth0: link state changed to DOWN
ngeth0: changing name to 'vi1_r1'
vi1_r1: link state changed to UP
ngeth1: Ethernet address: 58:9c:fc:10:ff:f3
ngeth1: link state changed to UP
ngeth1: link state changed to DOWN
ngeth1: changing name to 'vi2_r1'
vi2_r1: link state changed to UP
ng_ether_ifnet_arrival_event: can't re-name node vi1_r1
ng_ether_ifnet_arrival_event: can't re-name node vi2_r1
lo0: link state changed to UP
ngeth2: Ethernet address: 58:9c:fc:10:ff:89
ngeth2: link state changed to UP
ngeth2: link state changed to DOWN
ngeth2: changing name to 'vi1_vpnr1'
vi1_vpnr1: link state changed to UP
ngeth3: Ethernet address: 58:9c:fc:10:ff:cb
ngeth3: link state changed to UP
ngeth3: link state changed to DOWN
ngeth3: changing name to 'vri1_vpnr1'
vri1_vpnr1: link state changed to UP
ng_ether_ifnet_arrival_event: can't re-name node vi1_vpnr1
ng_ether_ifnet_arrival_event: can't re-name node vri1_vpnr1
lo0: link state changed to UP
ngeth4: Ethernet address: 58:9c:fc:10:77:66
ngeth4: link state changed to UP
ngeth4: link state changed to DOWN
ngeth4: changing name to 'vi2_vpnr2'
vi2_vpnr2: link state changed to UP
ngeth5: Ethernet address: 58:9c:fc:00:28:4c
ngeth5: link state changed to UP
ngeth5: link state changed to DOWN
ngeth5: changing name to 'vri2_vpnr2'
vri2_vpnr2: link state changed to UP
ng_ether_ifnet_arrival_event: can't re-name node vi2_vpnr2
ng_ether_ifnet_arrival_event: can't re-name node vri2_vpnr2
lo0: link state changed to UP
ngeth6: Ethernet address: 58:9c:fc:10:ff:eb
ngeth6: link state changed to UP
ngeth6: link state changed to DOWN
ngeth6: changing name to 'vri1_vpnh1'
vri1_vpnh1: link state changed to UP
ng_ether_ifnet_arrival_event: can't re-name node vri1_vpnh1
lo0: link state changed to UP
ngeth7: Ethernet address: 58:9c:fc:10:ff:ef
ngeth7: link state changed to UP
ngeth7: link state changed to DOWN
ngeth7: changing name to 'vri2_vpnh2'
vri2_vpnh2: link state changed to UP
ng_ether_ifnet_arrival_event: can't re-name node vri2_vpnh2
lo0: link state changed to UP
```

The errors didn't change even after appending the following modules to `/boot/loader.conf`:

```
netgraph_load="YES"
ng_netflow_load="YES"
ng_ksocket_load="YES"
ng_ether_load="YES"
ng_bridge_load="YES"
ng_eiface_load="YES"
ng_socket_load="YES"
```

Any clue? Thanks!

**Comment by zenny** [comment]
Hi again,

`ng_ether_ifnet_arrival_event: can't re-name node vi0_v1`

UPSTREAM BUG RECURRENCE: epair-MAC address issue as above appears to be a recurrence of something that reportedly been solved in 2014 from:

https://blog.plitc.eu/2014/freebsd-10-vimage-virtualized-network-stack-mit-if_bridge-epair/ which led me to https://github.com/lattera/freebsd/commit/624482876fe019bc1a74bfc3d6f690ac9bdf3196, but the proposed patch was only for epair-bridge, not netgraph, and therefore https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=241954 might have been filed.

A further investigation led me to some interesting pointers, but all of them are with epair, not netgraph as follows:

https://redmine.ixsystems.com/issues/20967
https://www.truenas.com/community/threads/ng_ether_ifnet_arrival_event-cant-re-name-node-epair0b.26196/

Just for your info.

Thanks @genneko for the great tool and enlightening write ups!

Cheers and stay safe,

**Comment by genneko** [comment]
Hi @zenny
Thanks for the info and sorry to reply so late.
I've been wanting to try 13 but haven't done it yet.
I will look at this when I have time to setup 13 on a VM or whatever shortly.

**Comment by zenny** [comment]
https://github.com/genneko/freebsd-vimage-jails/commit/3abed26d4cf3239c34758fba1509bafd77d77cb1 fixed the issue fantastically.

@genneko san, thanks for the bug fix. :D

**Comment by zenny** [comment]
An update:

Though it shows up without any warnings after the bug fix above:

```
[root@freebsd13 ~]# vnet list -r
vi0
  freebsd13(HOST) vi0 172.31.0.1/24
  v1 vi0_v1 172.31.0.101/24
  v2 vi0_v2 172.31.0.102/24
  v3 vi0_v3 172.31.0.103/24
vi1
  freebsd13(HOST) vi1 172.32.0.1/24
  c1 vi1_c1 172.32.0.101/24
  c2 vi1_c2 172.32.0.102/24
  c3 vi1_c3 172.32.0.103/24
```

Yet `dmesg`  still do report the renaming failure:

```
[root@freebsd13 ~]# dmesg | grep ng_ether
ng_ether_ifnet_arrival_event: can't re-name node vi0_v1
ng_ether_ifnet_arrival_event: can't re-name node vi0_v2
ng_ether_ifnet_arrival_event: can't re-name node vi0_v3
ng_ether_ifnet_arrival_event: can't re-name node vi1_c1
ng_ether_ifnet_arrival_event: can't re-name node vi1_c2
ng_ether_ifnet_arrival_event: can't re-name node vi1_c3
```

**Comment by genneko** [comment]
Hi @zenny, thank you for the update!

Oh, as I see those messages everytime I fire up a vnet jail but the interface is actually renamed, I almost ignore them without thinking any further.

But today I tried to figure out what causes the messages by looking at the source and using dtrace. Here is what I found.

*Please note that I'm just a hobbyist not a developer. So there might be some degree of inaccuracies and misunderstandings :p*

### Short version
- The message is output when an interface is moved from a host to a vnet jail (`ifconfig IFNAME vnet JAILNAME`).
- During the move operation, [ng_name_node()](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) function in sys/netgraph/ng_base.c is called twice.
- The second call returns EADDRINUSE because the interface has been already named that way by the first call and the second caller outputs the message from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L429).

I think it's the expected behavior and the message can be safely ignored, though the message is somewhat confusing as it makes no distinction between EINVAL and EADDRINUSE which may be returned by ng_name_node().

### Long version
- The message is output when an interface is moved from a host to a vnet jail (`ifconfig IFNAME vnet JAILNAME`).

- A single `ifconfig vnet` run invokes the following calls.

  1. ``ifconfig vnet`` issues an SIOCSIFVNET ioctl from [setifvnet()](https://github.com/freebsd/freebsd-src/blob/main/sbin/ifconfig/ifconfig.c#L1106) in sbin/ifconfig/ifconfig.c.
  2. The SIOCSIFVNET ioctl is handled by [ifhwioctl()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L2478)'s [switch statement](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L2730) in sys/net/if.c.
  3. ifhwioctl() calls [if_vmove_loan()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1384) in the same file, then it calls [if_vmove()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1303) in turn.
  4. In if_vmove(), [this section](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1350) calls ifp->if_reassign(), which points to [ether_reassign()](https://github.com/freebsd/freebsd-src/blob/26492ba2716f8b839f743bb663ce47405990fdf0/sys/net/if_ethersubr.c#L1034) in sys/net/if_ethersubr.c (in this case).
  5. ether_reassign() calls [ng_ether_attach()](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L303) in sys/netgraph/ng_ether.c through the function pointer ng_ether_attach_p.
  6. ng_ether_attach() registers the interface name in the vnet by calling [ng_name_node](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) in sys/netgraph/ng_base.c from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L344).
  7. Later in if_vmove(), [if_attach_internal()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L867) is called from [here](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1373) .
  8. if_attach_internal() invokes if_arrival_event from [here](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L998) and [ng_ether_ifnet_arrival_event()](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L402) in sys/netgraph/ng_ether.c is called.
  9. ng_ether_ifnet_arrival_event() calls [ng_name_node()](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) in sys/netgraph/ng_base.c from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L427).
  10. This second ng_name_node() call returns EADDRINUSE because the interface has been already named by the first call in step 6.
  11. ng_ether_ifnet_arrival_event() outputs the message from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L429).

### What I did
I used the following commands to see what happened when I moved an interface to a vnet jail.
- On a terminal,
  Create an ng_eiface virtual interface with vnet script.
  ```
  # vnet eiface testif
  ```
  Start dtrace to monitor ng_name_node() return values and stacktrace.
  ```
  # dtrace -n 'fbt:netgraph:ng_name_node:return { printf("%s %d", execname, arg1); stack(3); }'
  ```
- On another terminal,
  Create a vnet jail and move the interface from the host to the jail.
  ```
  # jail -c persist vnet=new name=testjail
  # ifconfig testif vnet testjail
  ```
  Or do this more quickly with the jail command's vnet.interface parameter. The command seems to run ifconfig vnet internally.
  ```
  # jail -c persist vnet=new vnet.interface=testif name=testjail
  ```
- Check dtrace output on the first terminal. The first one returns 0 while the second 48 (EADDRINUSE).
  ```
  CPU     ID                    FUNCTION:NAME
    3  74695              ng_name_node:return ifconfig 0
                ng_ether.ko`ng_ether_attach+0x14f
                kernel`ether_reassign+0x49
                kernel`if_vmove+0x12b
  
    3  74695              ng_name_node:return ifconfig 48
                ng_ether.ko`ng_ether_ifnet_arrival_event+0x98
                kernel`if_attach_internal+0x461
                kernel`if_vmove+0x2c5
  ```
- Clean up
  Move the interface back to the host.
  ```
  # ifconfig testif -vnet testjail
  ```
  Remove the jail.
  ```
  # jail -r testjail
  ```
  Remove the interface.
  ```
  # vnet eiface -d testif
  ```

**Comment by zenny** [comment]
> Hi @zenny, thank you for the update!
> 
> Oh, as I see those messages everytime I fire up a vnet jail but the interface is actually renamed, I almost ignore them without thinking any further.
> 
> But today I tried to figure out what causes the messages by looking at the source and using dtrace. Here is what I found.
> 
> _Please note that I'm just a hobbyist not a developer. So there might be some degree of inaccuracies and misunderstandings :p_
> ### Short version
> 
>     * The message is output when an interface is moved from a host to a vnet jail (`ifconfig IFNAME vnet JAILNAME`).
> 
>     * During the move operation, [ng_name_node()](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) function in sys/netgraph/ng_base.c is called twice.
> 
>     * The second call returns EADDRINUSE because the interface has been already named that way by the first call and the second caller outputs the message from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L429).
> 
> 
> I think it's the expected behavior and the message can be safely ignored, though the message is somewhat confusing as it makes no distinction between EINVAL and EADDRINUSE which may be returned by ng_name_node().
> ### Long version
> 
>     * The message is output when an interface is moved from a host to a vnet jail (`ifconfig IFNAME vnet JAILNAME`).
> 
>     * A single `ifconfig vnet` run invokes the following calls.
>       
>       1. `ifconfig vnet` issues an SIOCSIFVNET ioctl from [setifvnet()](https://github.com/freebsd/freebsd-src/blob/main/sbin/ifconfig/ifconfig.c#L1106) in sbin/ifconfig/ifconfig.c.
>       2. The SIOCSIFVNET ioctl is handled by [ifhwioctl()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L2478)'s [switch statement](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L2730) in sys/net/if.c.
>       3. ifhwioctl() calls [if_vmove_loan()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1384) in the same file, then it calls [if_vmove()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1303) in turn.
>       4. In if_vmove(), [this section](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1350) calls ifp->if_reassign(), which points to [ether_reassign()](https://github.com/freebsd/freebsd-src/blob/26492ba2716f8b839f743bb663ce47405990fdf0/sys/net/if_ethersubr.c#L1034) in sys/net/if_ethersubr.c (in this case).
>       5. ether_reassign() calls [ng_ether_attach()](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L303) in sys/netgraph/ng_ether.c through the function pointer ng_ether_attach_p.
>       6. ng_ether_attach() registers the interface name in the vnet by calling [ng_name_node](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) in sys/netgraph/ng_base.c from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L344).
>       7. Later in if_vmove(), [if_attach_internal()](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L867) is called from [here](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L1373) .
>       8. if_attach_internal() invokes if_arrival_event from [here](https://github.com/freebsd/freebsd-src/blob/092f3f081265c68cd8de0234ba8e46560ccc061e/sys/net/if.c#L998) and [ng_ether_ifnet_arrival_event()](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L402) in sys/netgraph/ng_ether.c is called.
>       9. ng_ether_ifnet_arrival_event() calls [ng_name_node()](https://github.com/freebsd/freebsd-src/blob/45d75e3ac3fb5bf8230ca28dc09b48c6e5ed7a4f/sys/netgraph/ng_base.c#L848) in sys/netgraph/ng_base.c from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L427).
>       10. This second ng_name_node() call returns EADDRINUSE because the interface has been already named by the first call in step 6.
>       11. ng_ether_ifnet_arrival_event() outputs the message from [here](https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/netgraph/ng_ether.c#L429).
> 
> 
> ### What I did
> 
> I used the following commands to see what happened when I moved an interface to a vnet jail.
> 
>     * On a terminal,
>       Create an ng_eiface virtual interface with vnet script.
>       ```
>       # vnet eiface testif
>       ```
>       
>       
>       Start dtrace to monitor ng_name_node() return values and stacktrace.
>       ```
>       # dtrace -n 'fbt:netgraph:ng_name_node:return { printf("%s %d", execname, arg1); stack(3); }'
>       ```
> 
>     * On another terminal,
>       Create a vnet jail and move the interface from the host to the jail.
>       ```
>       # jail -c persist vnet=new name=testjail
>       # ifconfig testif vnet testjail
>       ```
>       
>       
>       Or do this more quickly with the jail command's vnet.interface parameter. The command seems to run ifconfig vnet internally.
>       ```
>       # jail -c persist vnet=new vnet.interface=testif name=testjail
>       ```
> 
>     * Check dtrace output on the first terminal. The first one returns 0 while the second 48 (EADDRINUSE).
>       ```
>       CPU     ID                    FUNCTION:NAME
>         3  74695              ng_name_node:return ifconfig 0
>                     ng_ether.ko`ng_ether_attach+0x14f
>                     kernel`ether_reassign+0x49
>                     kernel`if_vmove+0x12b
>       
>         3  74695              ng_name_node:return ifconfig 48
>                     ng_ether.ko`ng_ether_ifnet_arrival_event+0x98
>                     kernel`if_attach_internal+0x461
>                     kernel`if_vmove+0x2c5
>       ```
> 
>     * Clean up
>       Move the interface back to the host.
>       ```
>       # ifconfig testif -vnet testjail
>       ```
>       
>       
>       Remove the jail.
>       ```
>       # jail -r testjail
>       ```
>       
>       
>       Remove the interface.
>       ```
>       # vnet eiface -d testif
>       ```

@genneko How explicitly you explained the debug process! Admirable! :100:
